### ISSUE TITLE
 GacGen/NativeController.cpp should be removed from CMakeLists.txt

### ISSUE THREAD

**Issue by jimwang118** [vczh-libraries/GacUI#103]
The NativeController.cpp file does not exist in the project and should be deleted from the Tools/GacGen/CMakeLists.txt compilation file.

**Comment by vczh** [comment]
I will close this as **won't fix** since a more elegant solution is available as I have commented in the vcpkg link above.

**Comment by BillyONeal** [comment]
> I will close this as **won't fix** since a more elegant solution is available as I have commented in the vcpkg link above.

I'm not sure what is more 'elegant' in your description; we use upstream's build system unless it is entirely unusable for some reason because we aren't the maintainers and often our forked build systems are a source of mistakes that confuse library authors and users.

**Comment by vczh** [comment]
@BillyONeal The problem of the last version is that, vcpkg used source files from 4 repos at the same time. This is not right because no one can ensure the 4 commits taken from 4 repo are sync. But at that moment I didn't solve this issue for some reason.

Now the blocking issue preventing vcpkg to use only one `Release` repo has gone. These `CMakeLists.txt` are in other repos, so they can't be used anymore. I use vcxproj instead of cmake to build my repo, but even if cmake is better, these files should be in the `Release` repo. So deleting them from this `GacUI` repo is going to happen anyway.
