### ISSUE TITLE
DPI support

### ISSUE THREAD

**Issue by kitsek** [vczh-libraries/GacUI#18]
Please add HiDPI support~
if gacui supports game engine that'll be great.

**Comment by vczh** [comment]
If you read my Direct2D code you will see I manually unsupport HI DPI settings, because as a one man army the performance is definitely not good enough for such a big library.

But you can add it yourself just for your game!
* Use Direct2D, find the "dpi = 96" code and delete it.
* Add your manifest to support HI DPI.
* Modify the Direct2D initialization code to support your target Direct3D devices.
* Expose your Direct3D devices to GuiDirect2DElement.

Than you should be fine, because now the application uses the real DPI coordinate. If you finish the job you can create a pull request to me. I will modify it to support other scenarios.

**Comment by vczh** [comment]
create another issue #37 to track this problem and close this for duplication
